gazebo:
  auto_disable_bodies: false
  cfm: 0.0
  contact_max_correcting_vel: 100.0
  contact_surface_layer: 0.001
  erp: 0.2
  gravity_x: 0.0
  gravity_y: 0.0
  gravity_z: -9.8
  max_contacts: 20
  max_update_rate: 1000.0
  sor_pgs_iters: 50
  sor_pgs_precon_iters: 0
  sor_pgs_rms_error_tol: 0.0
  sor_pgs_w: 1.3
  time_step: 0.001
rosdistro: 'noetic

  '
roslaunch:
  uris:
    host_ubuntu__34517: http://ubuntu:34517/
    host_ubuntu__36349: http://ubuntu:36349/
    host_ubuntu__39167: http://ubuntu:39167/
    host_ubuntu__41515: http://ubuntu:41515/
    host_ubuntu__42213: http://ubuntu:42213/
rosversion: '1.15.14

  '
run_id: 1bb18958-2cf4-11ed-a71e-8d2088f423c9
sime:
  background_b: 255
  background_g: 86
  background_r: 69
turtle1_tf_broadcaster:
  turtle: turtle1
turtle2_tf_broadcaster:
  turtle: turtle2
turtlesim:
  background_b: 255
  background_g: 86
  background_r: 150
use_sim_time: true
