<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="mycar">
    <xacro:property name="camera_x" value="0.02"/>
    <xacro:property name="camera_y" value="0.05"/>
    <xacro:property name="camera_z" value="0.05"/>
    <xacro:property name="joint_camera_x" value="0.08"/>
    <xacro:property name="joint_camera_y" value="0"/>
    <xacro:property name="joint_camera_z" value="${baselink_length / 2 + camera_z / 2}"/>
    
    
    
    
    
    
    <link name="camera">
        <visual name="camera">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${camera_x} ${camera_y} ${camera_z}"/>
            </geometry>
            <material name="black">
                <color rgba="0.0 0.0 0.0 1.0"/>
            </material>
        </visual>
        
    </link>
    <joint name="camera2base" type="fixed">
        <parent link="base_link"/>
        <child link="camera"/>
        <origin xyz="${joint_camera_x} ${joint_camera_y} ${joint_camera_z}" rpy="0 0 0"/>
    </joint>
    
</robot>