<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="mycar">
    <xacro:property name="PI" value="3.1415926"/>
    <xacro:property name="footprint_radius" value="0.001"/>
    <xacro:property name="baselink_radius" value="0.1"/>
    <xacro:property name="baselink_length" value="0.08"/>
    <xacro:property name="baselink_height" value="0.015"/>
    
    
    
    <link name="base_footprint">
        <visual>
            <geometry>
                <sphere radius="${footprint_radius}"/>
            </geometry>
        </visual>
    </link>

    <link name="base_link">
        <visual>
            <geometry>
                <cylinder radius='${baselink_radius}' length='${baselink_length}'/>
            </geometry>

            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            
            <material name="base_link_color">
                <color rgba="1 0.5 0.2 0.5"/>
            </material>
        </visual>
    </link>
    <joint name="link2footprint" type="fixed">
        <origin xyz="0.0 0.0 ${baselink_height + baselink_length / 2}" rpy="0.0 0.0 0.0"/>
        <parent link="base_footprint"/>
        <child link="base_link"/>
    </joint>
    
    <xacro:macro name="getwheel" params="dire radius length lr">
        <link name="${dire}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <origin xyz="0.0 0.0 0.0" rpy="1.5708 0.0 0.0"/>
                <material name="wheel_color">
                    <color rgba="0.0 0.0 0.0 0.3"/>
                </material>
                
            </visual>
            
        </link>

        <joint name="${dire}2link" type="continuous">
            <origin xyz="0.0 ${lr * baselink_radius} -${baselink_height + baselink_length / 2 -radius}" rpy="0.0 0.0 0.0"/>
            <parent link="base_link"/>
            <child link="${dire}_wheel"/>
            <axis xyz="0.0 1 0.0"/>
            
        </joint>
    </xacro:macro>

    <xacro:macro name="autowheel" params="dire radius dis lr">
        <link name="${dire}_wheel">
            <visual>
                <geometry>
                    <sphere radius="${radius}"/>
                </geometry>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <material name="wheel_color">
                    <color rgba="0.0 0.0 0.0 0.3"/>
                </material>
            </visual>
        </link>
        
        <joint name="${dire}2link" type="continuous">
            <origin xyz="${lr * dis} 0 -${baselink_height + baselink_length / 2 - radius}" rpy="0.0 0.0 0.0"/>
            <parent link="base_link"/>
            <child link="${dire}_wheel"/>
            <axis xyz="0.0 1 0.0"/>
        </joint>
    </xacro:macro>

    <xacro:getwheel dire="left" radius="0.0325" length="0.015" lr="1"/>
    <xacro:getwheel dire="right" radius="0.0325" length="0.015" lr="-1"/>
    <xacro:autowheel dire="front" radius="0.0075" dis="0.08" lr="1"/>
    <xacro:autowheel dire="back" radius="0.0075" dis="0.08" lr="-1"/>

</robot>