<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="mycar">
    <!-- 1.属性定义 -->
    <xacro:property name="PI" value="3.1415927"/>
    <xacro:property name="radius" value="0.03"/>
    
    <!-- 2.属性调用 -->
    ${PI}
    ${radius/2}
    <!-- 3.数学运算 -->
    
</robot>